// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/mkaiho/go-auth-api/entity"
	mock "github.com/stretchr/testify/mock"
)

// IDGenerator is an autogenerated mock type for the IDGenerator type
type IDGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: ctx
func (_m *IDGenerator) Generate(ctx context.Context) (entity.ID, error) {
	ret := _m.Called(ctx)

	var r0 entity.ID
	if rf, ok := ret.Get(0).(func(context.Context) entity.ID); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(entity.ID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIDGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewIDGenerator creates a new instance of IDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIDGenerator(t mockConstructorTestingTNewIDGenerator) *IDGenerator {
	mock := &IDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
