// Code generated by mockery v2.19.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HashGenerator is an autogenerated mock type for the HashGenerator type
type HashGenerator struct {
	mock.Mock
}

// Compare provides a mock function with given fields: ctx, value, hashed
func (_m *HashGenerator) Compare(ctx context.Context, value []byte, hashed []byte) error {
	ret := _m.Called(ctx, value, hashed)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte) error); ok {
		r0 = rf(ctx, value, hashed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Generate provides a mock function with given fields: ctx, value
func (_m *HashGenerator) Generate(ctx context.Context, value []byte) ([]byte, error) {
	ret := _m.Called(ctx, value)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = rf(ctx, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHashGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewHashGenerator creates a new instance of HashGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHashGenerator(t mockConstructorTestingTNewHashGenerator) *HashGenerator {
	mock := &HashGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
